# Generated by Django 5.2.7 on 2025-11-06 11:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('username', models.CharField(blank=True, max_length=150, verbose_name='用户名 (可选)')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='账号激活状态')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='后台访问权限')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='注册时间')),
                ('license_key', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='许可证密钥')),
                ('user_key', models.TextField(blank=True, help_text='Base64编码的用户密钥（敏感信息），存储为 TEXT 类型以适应不确定长度。', null=True, verbose_name='用户密钥')),
                ('device_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='设备ID')),
                ('license_activated_at', models.DateTimeField(blank=True, null=True, verbose_name='许可证激活时间')),
                ('license_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='许可证到期时间')),
                ('license_active', models.BooleanField(db_index=True, default=False, verbose_name='许可证激活状态')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'accounts_user',
            },
        ),
        migrations.CreateModel(
            name='FileKey',
            fields=[
                ('file_id', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True, verbose_name='文件ID')),
                ('nonce', models.TextField(verbose_name='Nonce (base64)')),
                ('tag', models.TextField(verbose_name='Tag (base64)')),
                ('encrypted_key', models.TextField(verbose_name='加密的文件密钥 (base64)')),
                ('creator_device_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='创建设备ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_files', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '文件密钥',
                'verbose_name_plural': '文件密钥',
                'db_table': 'accounts_filekey',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['license_key'], name='accounts_us_license_a7c9dc_idx'),
        ),
        migrations.AddIndex(
            model_name='filekey',
            index=models.Index(fields=['creator_user', 'created_at'], name='accounts_fi_creator_bf8b77_idx'),
        ),
    ]
