# Generated by Django 5.2.7 on 2025-10-19 06:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_license'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileKey',
            fields=[
                ('file_id', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True, verbose_name='文件ID')),
                ('nonce', models.TextField(verbose_name='Nonce（base64）')),
                ('tag', models.TextField(verbose_name='Tag（base64）')),
                ('encrypted_key', models.TextField(verbose_name='加密的文件密钥（base64）')),
                ('creator_device_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='创建设备ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '文件密钥',
                'verbose_name_plural': '文件密钥',
                'db_table': 'file_keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='license',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AddField(
            model_name='user',
            name='device_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='设备ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='license_activated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='许可证激活时间'),
        ),
        migrations.AddField(
            model_name='user',
            name='license_active',
            field=models.BooleanField(default=False, verbose_name='许可证激活状态'),
        ),
        migrations.AddField(
            model_name='user',
            name='license_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='许可证过期时间'),
        ),
        migrations.AddField(
            model_name='user',
            name='license_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='许可证密钥'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_key',
            field=models.TextField(blank=True, help_text='base64编码的用户密钥（敏感信息）', null=True, verbose_name='用户密钥'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='注册时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='账号激活状态'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='管理员'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=100, verbose_name='用户名'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['license_key'], name='users_license_b53120_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
        migrations.AddField(
            model_name='filekey',
            name='creator_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_files', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.DeleteModel(
            name='License',
        ),
        migrations.AddIndex(
            model_name='filekey',
            index=models.Index(fields=['creator_user', 'created_at'], name='file_keys_creator_6ca77a_idx'),
        ),
    ]
