# Generated by Django 5.2.7 on 2025-10-19 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('user_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('active', '激活'), ('expired', '过期'), ('revoked', '已撤销')], default='active', max_length=10)),
                ('max_devices', models.IntegerField(default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DeviceActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=128)),
                ('decrypt_key', models.CharField(max_length=128)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activations', to='chatbot.license')),
            ],
            options={
                'unique_together': {('license', 'device_id')},
            },
        ),
    ]
